export const MODAL_BODY_TYPES = {
  USER_DETAIL: "USER_DETAIL",
  PRE_PROMPT_ADD_NEW : "PRE_PROMPT_ADD_NEW",
  PRE_PROMPT_UPDATE : "PRE_PROMPT_UPDATE",
  CLOSER_PROMPT_UPDATE : "CLOSER_PROMPT_UPDATE",
  CLOSER_PROMPT_ADD_NEW : "CLOSER_PROMPT_ADD_NEW",
  PUSH_PROMPT_ADD_NEW : "PUSH_PROMPT_ADD_NEW",
  PUSH_PROMPT_UPDATE : "PUSH_PROMPT_UPDATE",
  KNOWLEDGE_ADD_NEW : "KNOWLEDGE_ADD_NEW",
  KNOWLEDGE_UPDATE : "KNOWLEDGE_UPDATE",
  ASSISTANT_SETTING : "ASSISTANT_SETTING",
  ASSISTANT_ADD_NEW : "ASSISTANT_ADD_NEW",
  ASSISTANT_UPDATE : "ASSISTANT_UPDATE",
  CONFIRMATION: "CONFIRMATION",
  DEFAULT: "",
}

export const RIGHT_DRAWER_TYPES = {
  NOTIFICATION: "NOTIFICATION",
  CALENDAR_EVENTS: "CALENDAR_EVENTS",
}

export const CONFIRMATION_MODAL_CLOSE_TYPES = {
  PRE_PROMPT_DELETE: "PRE_PROMPT_DELETE",
  CLOSER_PROMPT_DELETE: "CLOSER_PROMPT_DELETE",
  PUSH_PROMPT_DELETE: "PUSH_PROMPT_DELETE",
  KNOWLEDGE_DELETE: "KNOWLEDGE_DELETE",
  ASSISTANT_DELETE: "ASSISTANT_DELETE",
}
